# Build /etc/moodle/env on VM from Key Vault (do not echo secrets).
param(
    [string]$VmHost = 'azureadmin@52.252.59.54',
    [string]$KeyVault = 'utkvnhhwegpz3rem6'
)

$ErrorActionPreference = 'Stop'
$env:Path = [System.Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path', 'User')

$dbpass = az keyvault secret show --vault-name $KeyVault --name moodle-app-password --query value -o tsv
$redis = az keyvault secret show --vault-name $KeyVault --name redis-password --query value -o tsv
$worker = az keyvault secret show --vault-name $KeyVault --name cf-worker-shared-secret --query value -o tsv
$streamkey = az keyvault secret show --vault-name $KeyVault --name cf-stream-signing-key --query value -o tsv

$envcontent = @"
# Generated by setup-moodle-env-vm.ps1 — do not commit
MOODLE_DB_HOST=127.0.0.1
MOODLE_DB_PORT=6432
MOODLE_DB_NAME=moodle
MOODLE_DB_USER=moodle_user
MOODLE_DB_PASSWORD=$dbpass
MOODLE_REDIS_HOST=understandtech-redis-prod.eastus2.redis.azure.net
MOODLE_REDIS_PORT=10000
MOODLE_REDIS_PASSWORD=$redis
MOODLE_WWWROOT=https://understandtech.app
AITUTOR_WORKER_SHARED_SECRET=$worker
"@

$temp = [System.IO.Path]::GetTempFileName()
[System.IO.File]::WriteAllText($temp, $envcontent)
scp -i "$env:USERPROFILE\.ssh\id_ed25519" -o BatchMode=yes $temp "${VmHost}:/tmp/moodle.env"
ssh -i "$env:USERPROFILE\.ssh\id_ed25519" -o BatchMode=yes $VmHost "sudo mv /tmp/moodle.env /etc/moodle/env && sudo chown root:www-data /etc/moodle/env && sudo chmod 640 /etc/moodle/env"
Remove-Item $temp -Force

$streamtemp = [System.IO.Path]::GetTempFileName()
[System.IO.File]::WriteAllText($streamtemp, $streamkey)
scp -i "$env:USERPROFILE\.ssh\id_ed25519" -o BatchMode=yes $streamtemp "${VmHost}:/tmp/cf-stream-signing-key.pem"
ssh -i "$env:USERPROFILE\.ssh\id_ed25519" -o BatchMode=yes $VmHost "sudo mv /tmp/cf-stream-signing-key.pem /etc/moodle/cf-stream-signing-key.pem && sudo chown root:www-data /etc/moodle/cf-stream-signing-key.pem && sudo chmod 640 /etc/moodle/cf-stream-signing-key.pem"
Remove-Item $streamtemp -Force

Write-Host 'moodle env and Stream signing PEM deployed to VM'
